main: tld.example.myplugin.Main
name: DAD
version: 0.1
author: Dalton W.
description: A plugin inspired by my D (A)nd D sessions.
commands:
  hello:
    description: says hello to the server.
    usage: /hello
